/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package igtw;

/**
 *
 * @author mymac
 */
public class GlobalTimesFrame extends javax.swing.JFrame {

    /**
     * Creates new form GlobalTimesFrame
     */
    public GlobalTimesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelEST = new javax.swing.JLabel();
        jLabelMDT = new javax.swing.JLabel();
        jLabelRio = new javax.swing.JLabel();
        jLabelUK = new javax.swing.JLabel();
        jLabelMos = new javax.swing.JLabel();
        jLabelMum = new javax.swing.JLabel();
        jLabelPDT = new javax.swing.JLabel();
        jLabelCST = new javax.swing.JLabel();
        jLabelUTC = new javax.swing.JLabel();
        jLabelBer = new javax.swing.JLabel();
        jLabelDub = new javax.swing.JLabel();
        jLabelSin = new javax.swing.JLabel();
        jLabelBei = new javax.swing.JLabel();
        jLabelTok = new javax.swing.JLabel();
        jLabelChi = new javax.swing.JLabel();
        jLabelSyd = new javax.swing.JLabel();
        jLabelAuc = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 265, -1, -1));

        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 265, -1, -1));

        jLabel1.setFont(new java.awt.Font("Corsiva Hebrew", 0, 28)); // NOI18N
        jLabel1.setText("Global Times");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 8, -1, 50));

        jLabelEST.setText("jLabel2");
        getContentPane().add(jLabelEST, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 70, -1, -1));

        jLabelMDT.setText("jLabel2");
        getContentPane().add(jLabelMDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 92, -1, -1));

        jLabelRio.setText("jLabel2");
        getContentPane().add(jLabelRio, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 114, -1, -1));

        jLabelUK.setText("jLabel2");
        getContentPane().add(jLabelUK, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 136, -1, -1));

        jLabelMos.setText("jLabel2");
        getContentPane().add(jLabelMos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabelMum.setText("jLabel2");
        getContentPane().add(jLabelMum, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 180, -1, -1));

        jLabelPDT.setText("jLabel2");
        getContentPane().add(jLabelPDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 70, -1, -1));

        jLabelCST.setText("jLabel2");
        getContentPane().add(jLabelCST, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 92, -1, -1));

        jLabelUTC.setText("jLabel2");
        getContentPane().add(jLabelUTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 114, -1, -1));

        jLabelBer.setText("jLabel2");
        getContentPane().add(jLabelBer, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 136, -1, -1));

        jLabelDub.setText("jLabel2");
        getContentPane().add(jLabelDub, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 158, -1, -1));

        jLabelSin.setText("jLabel2");
        getContentPane().add(jLabelSin, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 180, -1, -1));

        jLabelBei.setText("jLabel2");
        getContentPane().add(jLabelBei, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 202, -1, -1));

        jLabelTok.setText("jLabel2");
        getContentPane().add(jLabelTok, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 224, -1, -1));

        jLabelChi.setText("jLabel2");
        getContentPane().add(jLabelChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 202, -1, -1));

        jLabelSyd.setText("jLabel2");
        getContentPane().add(jLabelSyd, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 224, -1, -1));

        jLabelAuc.setText("jLabel2");
        getContentPane().add(jLabelAuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 243, -1, -1));

        jLabel2.setText("EDT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 70, -1, -1));

        jLabel3.setText("MDT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 92, -1, -1));

        jLabel4.setText("Rio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 114, -1, -1));

        jLabel5.setText("UK");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 136, -1, -1));

        jLabel6.setText("Mos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 158, -1, -1));

        jLabel7.setText("Mum");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 180, -1, -1));

        jLabel8.setText("Bei");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 202, -1, -1));

        jLabel9.setText("Tok");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 224, -1, -1));

        jLabel10.setText("Auc");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 243, -1, -1));

        jLabel11.setText("PDT");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 70, -1, -1));

        jLabel12.setText("CDT");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 92, -1, -1));

        jLabel13.setText(" UTC");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 114, -1, -1));

        jLabel14.setText("Ber");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 136, -1, -1));

        jLabel15.setText("Dub");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 158, -1, -1));

        jLabel16.setText("Sin");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 180, -1, -1));

        jLabel17.setText("Chi");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 202, -1, -1));

        jLabel18.setText("Syd");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 224, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

this.setVisible(false);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
ModesFrame mf = new ModesFrame();
mf.setVisible(true);

this.setVisible(false);

    }//GEN-LAST:event_jButton4ActionPerformed
        public String getJLabelEST(){
    return jLabelEST.getText();
    }
    public void setjLabelEST(String string){
    jLabelEST.setText(string);
    }
            public String getJLabelPDT(){
    return jLabelPDT.getText();
    }
      public void setjLabelPDT(String string){
    jLabelPDT.setText(string);
    }       
    public void setjLabelRio(String string){
    jLabelRio.setText(string);
    }
            public String getJLabelRio(){
    return jLabelRio.getText();
    }
    public void setjLabelMum(String string){
    jLabelMum.setText(string);
    }
            public String getJLabelMum(){
    return jLabelMum.getText();
    }
    public void setjLabelDub(String string){
    jLabelDub.setText(string);
    }
            public String getJLabeDub(){
    return jLabelDub.getText();
    }
    public void setjLabelSin(String string){
    jLabelSin.setText(string);
    }
            public String getJLabelSin(){
    return jLabelSin.getText();
    }
    public void setjLabelUK(String string){
    jLabelUK.setText(string);
    }
            public String getJLabelUK(){
    return jLabelUK.getText();
    }
    public void setjLabelUTC(String string){
    jLabelUTC.setText(string);
    }
            public String getJLabelUTC(){
    return jLabelUTC.getText();
    }
    public void setjLabelMos(String string){
    jLabelMos.setText(string);
    }        public String getJLabelMos(){
    return jLabelMos.getText();
    }
    public void setjLabelMDT(String string){
    jLabelMDT.setText(string);
    }        public String getJLabelMDT(){
    return jLabelMDT.getText();
    }
    public void setjLabelCST(String string){
    jLabelCST.setText(string);
    }        public String getJLabelCST(){
    return jLabelCST.getText();
    }
    public void setjLabelBer(String string){
    jLabelBer.setText(string);
    }        public String getJLabelBer(){
    return jLabelBer.getText();
    }
        public void setjLabelBei(String string){
    jLabelBei.setText(string);
    }        public String getJLabelBei(){
    return jLabelBei.getText();
    }
        public void setjLabelChi(String string){
    jLabelChi.setText(string);
    }        public String getJLabelChi(){
    return jLabelChi.getText();
    }
        public void setjLabelTok(String string){
    jLabelTok.setText(string);
    }        public String getJLabelTok(){
    return jLabelTok.getText();
    }
        public void setjLabelSyd(String string){
    jLabelSyd.setText(string);
    }        public String getJLabelSyd(){
    return jLabelSyd.getText();
    }
        public void setjLabelAuc(String string){
    jLabelAuc.setText(string);
    }        public String getJLabelAuc(){
    return jLabelAuc.getText();
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlobalTimesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlobalTimesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlobalTimesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlobalTimesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlobalTimesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAuc;
    private javax.swing.JLabel jLabelBei;
    private javax.swing.JLabel jLabelBer;
    private javax.swing.JLabel jLabelCST;
    private javax.swing.JLabel jLabelChi;
    private javax.swing.JLabel jLabelDub;
    private javax.swing.JLabel jLabelEST;
    private javax.swing.JLabel jLabelMDT;
    private javax.swing.JLabel jLabelMos;
    private javax.swing.JLabel jLabelMum;
    private javax.swing.JLabel jLabelPDT;
    private javax.swing.JLabel jLabelRio;
    private javax.swing.JLabel jLabelSin;
    private javax.swing.JLabel jLabelSyd;
    private javax.swing.JLabel jLabelTok;
    private javax.swing.JLabel jLabelUK;
    private javax.swing.JLabel jLabelUTC;
    // End of variables declaration//GEN-END:variables
}
